# action.yml
name: 'AWS SSM EKS Action'
description: 'Connects to eks with private endpoint using ssm session on bastion server'
inputs:
  AWS_ACCESS_KEY_ID:
    description: Your AWS_ACCESS_KEY_ID
    required: false
  AWS_SECRET_ACCESS_KEY:
    description: Your AWS_SECRET_ACCESS_KEY
    required: false
  AWS_REGION:
    description: The region of the cluster
    required: false
  CLUSTER_NAME:
    description: The name of the cluster you're using
    required: true
  BASTION_NAME:
    description: The name of the bastion server you're using
    required: false
  BASTION_ID:
    description: The instance id of the bastion server you're using
    required: false
  SSM_PORT:
    description: The local port used by ssm session manager
    required: false
  kubectl_cmd:
    description: The arguments that you want to pass through to the kubectl command
    required: true
outputs:
  cmd-out:
    description: The output of the aws ssm command
runs:
  using: 'docker'
  image: 'Dockerfile'
